server:
  port: 8080

spring:
  application:
    name: sis1
  profiles:
    active: "@spring.profiles.active@"

app:
  name: SIS 1
  environment: default
  max-items: 10
  support-email: support@example.com
  mood-audit:
    enabled: false
